import json
import os

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ytdlpgui(object):
    def setupUi(self, ytdlpgui):
        ytdlpgui.setObjectName("ytdlpgui")
        ytdlpgui.setEnabled(True)
        ytdlpgui.setFixedSize(700, 539)
        self.setWindowIcon(QtGui.QIcon(os.path.join(os.environ.get("PROJECT_PATH"), 'assets', 'yt-dlp-gui.ico')))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        ytdlpgui.setFont(font)
        ytdlpgui.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(ytdlpgui)
        self.centralwidget.setObjectName("centralwidget")
        self.gb_params = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_params.setGeometry(QtCore.QRect(20, 10, 421, 151))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.gb_params.setFont(font)
        self.gb_params.setObjectName("gb_params")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.gb_params)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 71, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.params_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.params_layout.setContentsMargins(0, 0, 0, 0)
        self.params_layout.setObjectName("params_layout")
        self.link_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.link_label.setObjectName("link_label")
        self.params_layout.addWidget(self.link_label)
        self.path_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.path_label.setObjectName("path_label")
        self.params_layout.addWidget(self.path_label)
        self.format_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.format_label.setObjectName("format_label")
        self.params_layout.addWidget(self.format_label)
        self.link_entry = QtWidgets.QLineEdit(self.gb_params)
        self.link_entry.setGeometry(QtCore.QRect(80, 30, 331, 20))
        self.link_entry.setObjectName("link_entry")
        self.folderpath = QtWidgets.QLineEdit(self.gb_params)
        self.folderpath.setStyleSheet("""QLineEdit { background-color: #F0F0F0; }""")
        self.folderpath.setReadOnly(True)
        self.folderpath.setGeometry(QtCore.QRect(80, 70, 305, 20))
        self.folderpath.setObjectName("folderpath")
        self.choose_path = QtWidgets.QToolButton(self.gb_params, clicked=self.get_folder_path)
        self.choose_path.setGeometry(QtCore.QRect(390, 70, 22, 20))
        self.choose_path.setObjectName("choose_path")
        self.cb_format = QtWidgets.QComboBox(self.gb_params)
        self.cb_format.currentTextChanged.connect(self.index_changed)
        self.cb_format.setGeometry(QtCore.QRect(80, 114, 69, 20))
        self.cb_format.setObjectName("cb_format")
        self.cb_format.addItem("")
        self.cb_format.addItem("")
        self.cb_format.addItem("")
        self.gb_embeds = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_embeds.setGeometry(QtCore.QRect(460, 9, 121, 151))
        self.gb_embeds.setObjectName("gb_embeds")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.gb_embeds)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 79, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.embeds_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.embeds_layout.setContentsMargins(0, 0, 0, 0)
        self.embeds_layout.setObjectName("embeds_layout")
        self.cb_meta = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cb_meta.setObjectName("cb_meta")
        self.embeds_layout.addWidget(self.cb_meta)
        self.cb_thumb = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cb_thumb.setObjectName("cb_thumb")
        self.embeds_layout.addWidget(self.cb_thumb)
        self.cb_subs = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cb_subs.setObjectName("cb_subs")
        self.embeds_layout.addWidget(self.cb_subs)
        self.gb_cpanel = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_cpanel.setGeometry(QtCore.QRect(600, 10, 81, 151))
        self.gb_cpanel.setObjectName("gb_cpanel")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.gb_cpanel)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 20, 41, 121))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.cpanel_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.cpanel_layout.setContentsMargins(0, 0, 0, 0)
        self.cpanel_layout.setObjectName("cpanel_layout")
        self.add_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3, clicked=self.add_download)
        self.add_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(os.environ.get("PROJECT_PATH"), "assets", "add.png")),
                       QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        self.add_btn.setIcon(icon)
        self.add_btn.setObjectName("add_btn")
        self.cpanel_layout.addWidget(self.add_btn)
        self.clear_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3, clicked=self.clear_list)
        self.clear_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(os.environ.get("PROJECT_PATH"), "assets", "clear.png")),
                        QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.clear_btn.setIcon(icon1)
        self.clear_btn.setObjectName("clear_btn")
        self.cpanel_layout.addWidget(self.clear_btn)
        self.download_btn = QtWidgets.QPushButton(self.verticalLayoutWidget_3, clicked=self.download_list)
        self.download_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.join(os.environ.get("PROJECT_PATH"), "assets", "download.png")),
                        QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.download_btn.setIcon(icon2)
        self.download_btn.setObjectName("download_btn")
        self.cpanel_layout.addWidget(self.download_btn)
        self.treew = QtWidgets.QTreeWidget(self.centralwidget)
        self.treew.setGeometry(QtCore.QRect(20, 170, 661, 351))
        self.treew.setHeaderLabels(['Title', 'Format', 'Size', 'Progress', 'Status', 'Speed', 'ETA', 'URL'])
        self.treew.headerItem().setTextAlignment(2, QtCore.Qt.AlignCenter)
        self.treew.headerItem().setTextAlignment(3, QtCore.Qt.AlignCenter)
        self.treew.headerItem().setTextAlignment(4, QtCore.Qt.AlignCenter)
        self.treew.headerItem().setTextAlignment(5, QtCore.Qt.AlignCenter)
        self.treew.headerItem().setTextAlignment(6, QtCore.Qt.AlignLeft)
        self.treew.hideColumn(7)
        self.treew.setAlternatingRowColors(True)
        self.treew.setColumnWidth(0, 200)
        self.treew.setColumnWidth(1, 80)
        self.treew.setColumnWidth(2, 80)
        self.treew.setColumnWidth(3, 80)
        self.treew.setColumnWidth(5, 80)
        self.treew.setColumnWidth(6, 80)
        ytdlpgui.setCentralWidget(self.centralwidget)
        self.startup_settings()
        QtCore.QMetaObject.connectSlotsByName(ytdlpgui)
        ytdlpgui.setWindowTitle("yt-dlp-gui")
        self.gb_params.setTitle("Parameters")
        self.link_label.setText("Link:")
        self.path_label.setText("Path:")
        self.format_label.setText("Format:")
        self.link_entry.setPlaceholderText("https://www.youtube.com/watch?v=KewM8VgPF2E")
        self.choose_path.setText("...")
        self.cb_format.setItemText(0, "best")
        self.cb_format.setItemText(1, "mp4")
        self.cb_format.setItemText(2, "mp3")
        self.gb_embeds.setTitle("Optional Embeds")
        self.cb_meta.setText("Metadata")
        self.cb_thumb.setText("Thumbnail")
        self.cb_subs.setText("Subtitles")
        self.gb_cpanel.setTitle("Control")

    def startup_settings(self):
        try:
            with open(os.path.join(os.environ.get("PROJECT_PATH"), 'settings.json'), 'r') as f:
                settings = json.load(f)
        except (FileNotFoundError, json.decoder.JSONDecodeError):
            with open(os.path.join(os.environ.get("PROJECT_PATH"), 'settings.json'), 'w') as f:
                settings = {"path": "", "geo_x": 625, "geo_y": 290, "format": 0, "metadata": 0, "subtitles": 0,
                            "thumbnail": 0}
                json.dump(settings, f, indent=4)
        self.folderpath.setText(settings["path"])
        self.setGeometry(QtCore.QRect(settings["geo_x"], settings["geo_y"], 700, 539))
        self.cb_format.setCurrentIndex(settings["format"])
        self.cb_meta.setCheckState(settings["metadata"])
        self.cb_subs.setCheckState(settings["subtitles"])
        self.cb_thumb.setCheckState(settings["thumbnail"])
